In [12]:
# Keras import
import keras
from keras.datasets import cifar10
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten, Activation

# Sklearn import
import sklearn
from sklearn.model_selection import train_test_split

In [13]:
(X_train, y_train), (X_test, y_test) = cifar10.load_data()

In [14]:
num_classes = 10
print("X_train shape: {}".format(X_train.shape))
print("y_train shape: {}".format(y_train.shape))
print("X_test shape: {}".format(X_test.shape))
print("y_test shape: {}".format(y_test.shape))

X_train shape: (50000, 32, 32, 3)
y_train shape: (50000, 1)
X_test shape: (10000, 32, 32, 3)
y_test shape: (10000, 1)


In [15]:
print(y_train[0])
print()
print(X_train[0])
print()
print(X_train[0][0])
print()
print(X_train[0][0][0])
print()
print(X_train[0][0][0][0])

[6]

[[[ 59  62  63]
  [ 43  46  45]
  [ 50  48  43]
  ...
  [158 132 108]
  [152 125 102]
  [148 124 103]]

 [[ 16  20  20]
  [  0   0   0]
  [ 18   8   0]
  ...
  [123  88  55]
  [119  83  50]
  [122  87  57]]

 [[ 25  24  21]
  [ 16   7   0]
  [ 49  27   8]
  ...
  [118  84  50]
  [120  84  50]
  [109  73  42]]

 ...

 [[208 170  96]
  [201 153  34]
  [198 161  26]
  ...
  [160 133  70]
  [ 56  31   7]
  [ 53  34  20]]

 [[180 139  96]
  [173 123  42]
  [186 144  30]
  ...
  [184 148  94]
  [ 97  62  34]
  [ 83  53  34]]

 [[177 144 116]
  [168 129  94]
  [179 142  87]
  ...
  [216 184 140]
  [151 118  84]
  [123  92  72]]]

[[ 59  62  63]
 [ 43  46  45]
 [ 50  48  43]
 [ 68  54  42]
 [ 98  73  52]
 [119  91  63]
 [139 107  75]
 [145 110  80]
 [149 117  89]
 [149 120  93]
 [131 103  77]
 [125  99  76]
 [142 115  91]
 [144 112  86]
 [137 105  79]
 [129  97  71]
 [137 106  79]
 [134 106  76]
 [124  97  64]
 [139 113  78]
 [139 112  75]
 [133 105  69]
 [136 105  74]
 [139 108  77]
 [15

In [16]:
X_train = X_train.reshape(50000, 3072)
X_test = X_test.reshape(10000, 3072)
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')
X_train /= 255
X_test /= 255

print("X_train shape: {}".format(X_train.shape))
print("X_test shape: {}".format(X_test.shape))

X_train shape: (50000, 3072)
X_test shape: (10000, 3072)


In [17]:
y_train = keras.utils.to_categorical(y_train, num_classes)
y_test = keras.utils.to_categorical(y_test, num_classes)

print("y_train shape: {}".format(y_train.shape))
print("y_test shape: {}".format(y_test.shape))
print(y_train[0])

y_train shape: (50000, 10)
y_test shape: (10000, 10)
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]


In [18]:
model = Sequential()
model.add(Dense(512, activation='relu', input_shape=(3072,)))
model.add(Dense(512, activation='relu'))
model.add(Dense(num_classes, activation='softmax'))

model.summary()
model.compile(
            loss=keras.losses.categorical_crossentropy,
            optimizer='adam',
            metrics=['accuracy']
)

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 512)               1573376   
_________________________________________________________________
dense_2 (Dense)              (None, 512)               262656    
_________________________________________________________________
dense_3 (Dense)              (None, 10)                5130      
Total params: 1,841,162
Trainable params: 1,841,162
Non-trainable params: 0
_________________________________________________________________


In [19]:
model.fit(
    X_train, 
    y_train,
    epochs=10,
    batch_size=100,
    verbose=1
)

Epoch 1/10
50000/50000 [==============================] - 8s 151us/step - loss: 1.8738 - acc: 0.3278
Epoch 2/10
50000/50000 [==============================] - 7s 142us/step - loss: 1.6638 - acc: 0.4057
Epoch 3/10
50000/50000 [==============================] - 7s 141us/step - loss: 1.5775 - acc: 0.4367
Epoch 4/10
50000/50000 [==============================] - 7s 141us/step - loss: 1.5198 - acc: 0.4583
Epoch 5/10
50000/50000 [==============================] - 7s 141us/step - loss: 1.4679 - acc: 0.4770
Epoch 6/10
50000/50000 [==============================] - 7s 142us/step - loss: 1.4300 - acc: 0.4924
Epoch 7/10
50000/50000 [==============================] - 7s 145us/step - loss: 1.4024 - acc: 0.5026
Epoch 8/10
50000/50000 [==============================] - 7s 146us/step - loss: 1.3770 - acc: 0.5083
Epoch 9/10
50000/50000 [==============================] - 7s 147us/step - loss: 1.3460 - acc: 0.5205
Epoch 10/10
50000/50000 [==============================] - 7s 148us/step - loss: 1.3180 - a

In [20]:
score = model.evaluate(X_test, y_test, verbose=0)
print('Test loss:', score[0])
print('Test accuracy: {}%'.format(score[1]*100))

Test loss: 1.42718703956604
Test accuracy: 49.59%
