In [11]:
# Keras import
import keras
from keras.datasets import cifar10
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten, Activation

# Sklearn import
import sklearn
from sklearn.model_selection import train_test_split

In [12]:
(X_train, y_train), (X_test, y_test) = cifar10.load_data()

In [13]:
num_classes = 10
print("X_train shape: {}".format(X_train.shape))
print("y_train shape: {}".format(y_train.shape))
print("X_test shape: {}".format(X_test.shape))
print("y_test shape: {}".format(y_test.shape))

X_train shape: (50000, 32, 32, 3)
y_train shape: (50000, 1)
X_test shape: (10000, 32, 32, 3)
y_test shape: (10000, 1)


In [14]:
print(y_train[0])
print()
print(X_train[0])
print()
print(X_train[0][0])
print()
print(X_train[0][0][0])
print()
print(X_train[0][0][0][0])

[6]

[[[ 59  62  63]
  [ 43  46  45]
  [ 50  48  43]
  ...
  [158 132 108]
  [152 125 102]
  [148 124 103]]

 [[ 16  20  20]
  [  0   0   0]
  [ 18   8   0]
  ...
  [123  88  55]
  [119  83  50]
  [122  87  57]]

 [[ 25  24  21]
  [ 16   7   0]
  [ 49  27   8]
  ...
  [118  84  50]
  [120  84  50]
  [109  73  42]]

 ...

 [[208 170  96]
  [201 153  34]
  [198 161  26]
  ...
  [160 133  70]
  [ 56  31   7]
  [ 53  34  20]]

 [[180 139  96]
  [173 123  42]
  [186 144  30]
  ...
  [184 148  94]
  [ 97  62  34]
  [ 83  53  34]]

 [[177 144 116]
  [168 129  94]
  [179 142  87]
  ...
  [216 184 140]
  [151 118  84]
  [123  92  72]]]

[[ 59  62  63]
 [ 43  46  45]
 [ 50  48  43]
 [ 68  54  42]
 [ 98  73  52]
 [119  91  63]
 [139 107  75]
 [145 110  80]
 [149 117  89]
 [149 120  93]
 [131 103  77]
 [125  99  76]
 [142 115  91]
 [144 112  86]
 [137 105  79]
 [129  97  71]
 [137 106  79]
 [134 106  76]
 [124  97  64]
 [139 113  78]
 [139 112  75]
 [133 105  69]
 [136 105  74]
 [139 108  77]
 [15

In [15]:
X_train = X_train.reshape(50000, 3072)
X_test = X_test.reshape(10000, 3072)
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')

def dataset_minmax(dataset):
    minmax = list()
    for i in range(len(dataset[0])):
        col_values = [row[i] for row in dataset]
        value_min = min(col_values)
        value_max = max(col_values)
        minmax.append([value_min, value_max])
    return minmax

def normalize_dataset(dataset, minmax):
    for row in dataset:
        for i in range(len(row)):
            row[i] = (row[i] - minmax[i][0]) / (minmax[i][1] - minmax[i][0])
            
minmax = dataset_minmax(X_train)
normalize_dataset(X_train, minmax)

minmax = dataset_minmax(X_test)
normalize_dataset(X_test, minmax)

print("X_train shape: {}".format(X_train.shape))
print("X_test shape: {}".format(X_test.shape))

X_train shape: (50000, 3072)
X_test shape: (10000, 3072)


In [16]:
y_train = keras.utils.to_categorical(y_train, num_classes)
y_test = keras.utils.to_categorical(y_test, num_classes)

print("y_train shape: {}".format(y_train.shape))
print("y_test shape: {}".format(y_test.shape))
print(y_train[0])

y_train shape: (50000, 10)
y_test shape: (10000, 10)
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]


In [17]:
model = Sequential()
model.add(Dense(1024, activation='relu', input_shape=(3072,)))
model.add(Dense(1024, activation='relu'))
model.add(Dense(num_classes, activation='softmax'))

model.summary()
model.compile(
            loss=keras.losses.categorical_crossentropy,
            optimizer='adam',
            metrics=['accuracy']
)

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_4 (Dense)              (None, 1024)              3146752   
_________________________________________________________________
dense_5 (Dense)              (None, 1024)              1049600   
_________________________________________________________________
dense_6 (Dense)              (None, 10)                10250     
Total params: 4,206,602
Trainable params: 4,206,602
Non-trainable params: 0
_________________________________________________________________


In [18]:
model.fit(
    X_train, 
    y_train,
    epochs=20,
    batch_size=100,
    verbose=1
)

Epoch 1/20
50000/50000 [==============================] - 19s 390us/step - loss: 1.8871 - acc: 0.3272
Epoch 2/20
50000/50000 [==============================] - 20s 394us/step - loss: 1.6656 - acc: 0.4051
Epoch 3/20
50000/50000 [==============================] - 21s 414us/step - loss: 1.5701 - acc: 0.4365
Epoch 4/20
50000/50000 [==============================] - 22s 447us/step - loss: 1.5106 - acc: 0.4580
Epoch 5/20
50000/50000 [==============================] - 20s 405us/step - loss: 1.4631 - acc: 0.4770
Epoch 6/20
50000/50000 [==============================] - 20s 393us/step - loss: 1.4346 - acc: 0.4846
Epoch 7/20
50000/50000 [==============================] - 20s 396us/step - loss: 1.3999 - acc: 0.4975
Epoch 8/20
50000/50000 [==============================] - 20s 395us/step - loss: 1.3759 - acc: 0.5072
Epoch 9/20
50000/50000 [==============================] - 20s 400us/step - loss: 1.3438 - acc: 0.5175
Epoch 10/20
50000/50000 [==============================] - 20s 399us/step - loss: 

In [19]:
score = model.evaluate(X_test, y_test, verbose=0)
print('Test loss:', score[0])
print('Test accuracy: {}%'.format(score[1]*100))

Test loss: 1.4542933282852173
Test accuracy: 51.06%
